<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="LAPTOP-P330KRMQ"><DocLocation><![CDATA[E:\UFT Classbook PDF\Apollo (COVID-19)\HybridDrivenFramework\Driver\appnt]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[appnt]]></DName>
<Res><![CDATA[Res206]]></Res>
<RunType fmStep="True" /><DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[09-04-2022 - 22:55:37]]></Time>
<TimeTick>1649525137</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[09-04-2022 - 22:55:37]]></Time>
<TimeTick>1649525137</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="10" status="Passed" Source="Action1" SourceLine="213" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="9" status="Passed" Source="Action1" SourceLine="213" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Apollo 247 - Online Doctor]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[09-04-2022 - 22:55:42]]></Time>
<TimeTick>1649525142</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Apollo 247 - Online Doctor]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[09-04-2022 - 22:55:42]]></Time>
<TimeTick>1649525142</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Appointments.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-04-2022 - 22:55:42]]></Time>
<TimeTick>1649525142</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Action1" SourceLine="215" >
<Disp><![CDATA[Appointments.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" Source="Action1" SourceLine="215" >
<Disp><![CDATA[Apollo 247 - Online Doctor]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="13" Source="Action1" SourceLine="215" >
<Disp><![CDATA[Apollo 247 - Online Doctor]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Browser_2]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[09-04-2022 - 22:55:42]]></Time>
<TimeTick>1649525142</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Page_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[09-04-2022 - 22:55:42]]></Time>
<TimeTick>1649525142</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[VIEW DETAILS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-04-2022 - 22:55:42]]></Time>
<TimeTick>1649525142</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" Source="Action1" SourceLine="216" >
<Disp><![CDATA[VIEW DETAILS.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="20" Source="Action1" SourceLine="216" >
<Disp><![CDATA[Page_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="19" Source="Action1" SourceLine="216" >
<Disp><![CDATA[Browser_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Apollo]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[09-04-2022 - 22:55:44]]></Time>
<TimeTick>1649525144</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Apollo_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[09-04-2022 - 22:55:44]]></Time>
<TimeTick>1649525144</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[MANAGE.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-04-2022 - 22:55:44]]></Time>
<TimeTick>1649525144</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="27" Source="Action1" SourceLine="217" >
<Disp><![CDATA[MANAGE.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="26" Source="Action1" SourceLine="217" >
<Disp><![CDATA[Apollo_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Apollo_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[09-04-2022 - 22:55:44]]></Time>
<TimeTick>1649525144</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Cancel Appointment.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-04-2022 - 22:55:44]]></Time>
<TimeTick>1649525144</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="31" Source="Action1" SourceLine="218" >
<Disp><![CDATA[Cancel Appointment.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Cancel Consult.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-04-2022 - 22:55:44]]></Time>
<TimeTick>1649525144</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="34" Source="Action1" SourceLine="219" >
<Disp><![CDATA[Cancel Consult.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA["<iframe src='https://www.googl"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[09-04-2022 - 22:56:06]]></Time>
<TimeTick>1649525166</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="73" status="Warning" Source="Action1" SourceLine="220" >
<Disp><![CDATA["<iframe src='https://www.googl"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA["<iframe src='https://www.googl"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=WebElement<br>innertext=&ltiframe src="https://www.googletagmanager.com/ns.html?id=GTM-PNGHP4L&gtm_auth=&gtm_preview=&gtm_cookies_win=x" height="0" width="0" style="display:none;visibility:hidden" id="tag-manager"&gt&lt/iframe&gt Your browser does not support JavaScript! AppointmentsHealth Records MedicinesLab TestsCovid-190Consult RoomMANAGEDr Aakanksha Chawla JainPulmonology/ Respiratory Medicine | 9 YrsMOREMD (Pulmonary Medicine), IDCCM, IFCCM (Indian Fellowship in Critical Care Medicine)NAPCON 2020, Chairperson - Debate on COVID – 19, Criticare 2020 - Mechincal Ventilation, IAMIcon 2019 - Panelist COPDApollo Hospitals IndraprasthaEnglish, HindiOnline ConsultationRs. 1100Clinic visitRs. 1100Consult On14/04 at 01:30 pmAppointment Details14 Apr 2022, 1:30 PMApollo Hospitals Indraprastha Indraprastha Apollo Hospitals, Sarita Vihar,, Delhi-Mathura Road South Delhi, DelhiTotal ChargesTo Pay Rs. 1100One-time Hospital Registration Charges might be applicable for new users. var webengage; const licenseCode = 'in~~c2ab3533'; !(function(w, e, b, n, g) { function o(e, t) { e[t[t.length - 1]] = function() { r.__queue.push([t.join('.'), arguments]); }; } var i, s, r = w[b], z = ' ', l = 'init options track screen onReady'.split(z), a = 'feedback survey notification'.split(z), c = 'options render clear abort'.split(z), p = 'Open Close Submit Complete View Click'.split(z), u = 'identify login logout setAttribute'.split(z); if (!r || !r.__v) { for (w[b] = r = { __queue: [], __v: '6.0', user: {} }, i = 0; i &lt l.length; i++) o(r, [l[i]]); for (i = 0; i &lt a.length; i++) { for (r[a[i]] = {}, s = 0; s &lt c.length; s++) o(r[a[i]], [a[i], c[s]]); for (s = 0; s &lt p.length; s++) o(r[a[i]], [a[i], 'on' + p[s]]); } for (i = 0; i &lt u.length; i++) o(r.user, ['user', u[i]]); setTimeout(function() { var f = e.createElement('script'), d = e.getElementById('_webengage_script_tag'); (f.type = 'text/javascript'), (f.async = !0), (f.src = ('https:' == e.location.protocol ? 'https://widgets.in.webengage.com' : 'http://widgets.in.webengage.com') + '/js/webengage-min-v-6.0.js'), d.parentNode.insertBefore(f, d); }); } })(window, document, 'webengage'); webengage.init(licenseCode); var clevertap = { event: [], profile: [], region: 'in1', account: [], onUserLogin: [], notifications: [], privacy: [], }; clevertap.account.push({ id: '679-WZ9-4W6Z' }); (function() { var wzrk = document.createElement('script'); wzrk.type = 'text/javascript'; wzrk.async = true; wzrk.src = ('https:' == document.location.protocol ? 'https://d2r1yp2w7bby2u.cloudfront.net' : 'http://static.clevertap.com') + '/js/a.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(wzrk, s); })(); #webklipper-publisher-widget-container, #webklipper-publisher-widget-container * {overflow:visible; -webkit-box-sizing: content-box; -moz-box-sizing: content-box; box-sizing: content-box; margin: 0; padding: 0; border: 0; font-size: 100%; font: inherit; vertical-align: baseline;}var s=document.createElement("link");s.href="https://www.google-analytics.com";s.rel="preconnect";s.setAttribute("crossorigin","");document.head.append(s);var dtfn=google_tag_manager["GTM-PNGHP4L"].macro(13),lurl=document.location.href,urlHost=document.location.host,referrerUrl=document.referrer,referrerHost=document.referrer.split("/")[2];function getParameterByName(a){var b=window.location.href;a=a.replace(/[\[\]]/g,"\\$\x26");a=new RegExp("[?\x26]"+a+"(\x3d([^\x26#]*)|\x26|#|$)");return(b=a.exec(b))?b[2]?decodeURIComponent(b[2].replace(/\+/g," ")):"":"NA"} var sourceutm=getParameterByName("utm_source"),mediumutm=getParameterByName("utm_medium"),campaignutm=getParameterByName("utm_campaign"),termutm=getParameterByName("utm_term"),contentutm=getParameterByName("utm_content"),idutm=getParameterByName("utm_id"),gclidutm=getParameterByName("gclid"),fbclidutm=getParameterByName("fbclid"); if("NA"!=sourceutm||"NA"!=mediumutm||"NA"!=campaignutm||"NA"!=termutm||"NA"!=contentutm||"NA"!=idutm)dtfn("gtm_url",lurl,7),dtfn("gtm_source",sourceutm,7),dtfn("gtm_medium",mediumutm,7),dtfn("gtm_campaign",campaignutm,7),dtfn("gtm_term",termutm,7),dtfn("gtm_content",contentutm,7),dtfn("gtm_id",idutm,7); "apollo247.com"!==referrerHost&&"covid.apollo247.com"!==referrerHost&&"securegw.paytm.in"!==referrerHost&&"securegw-stage.paytm.in"!==referrerHost&&"apollo247.onelink.me"!==referrerHost&&"apl247.onelink.me"!==referrerHost&&""!==referrerUrl&&referrerHost!=urlHost&&dtfn("gtm_referrer",referrerUrl,7); var dtlyr=dataLayer,evntdtlyr=dtlyr.map(function(a){return a=a.event}),pagvwexst=evntdtlyr.includes("pageviewEvent");pagvwexst||dataLayer.push({event:"pageviewEvent",pageName:"Others",pageLOB:"Others",pageType:"Others"}); var btn=document.getElementsByClassName("afb-download-button").length;if(btn!=0&&!("Others".indexOf("Listing Page")&gt0&&"Others"=="Consultation"))AF("banners","hideBanner");var btn=document.getElementsByClassName("afb-download-button").length;if(btn!=0&&!("Chat Room Page".indexOf("Listing Page")&gt0&&"Consultation"=="Consultation"))AF("banners","hideBanner");var dtfn=google_tag_manager["GTM-PNGHP4L"].macro(54); if("UserLoggedIn"=="UserLoggedIn"){var dataly=window.dataLayer;var datalylen=dataly.length;var chckind=-1;for(var j=datalylen-1;j&gt=0;j--)if(dataly[j]["event"]=="UserLoggedIn"){chckind=j;break}var runcode=chckind==-1?false:dataly[chckind-1]["event"]=="OTPValidation Failed"?false:true;if(runcode){if("96b1b5c1-698f-4d8a-a160-1cef1d5d1f53"==undefined||"96b1b5c1-698f-4d8a-a160-1cef1d5d1f53"==null||"96b1b5c1-698f-4d8a-a160-1cef1d5d1f53"=="null"||"96b1b5c1-698f-4d8a-a160-1cef1d5d1f53"=="undefined")if("Login"=="Login")dataLayer.push({"event":"Log In"}); else dataLayer.push({"event":"Registration"});dtfn("gtm_userid","96b1b5c1-698f-4d8a-a160-1cef1d5d1f53",30)}}else{dataLayer.push({"event":"Log Out"});dtfn("gtm_userid",null,30)}; Cancel ConsultationWhy are you cancelling this consultation?Select reason for cancellingAdd Comments (Optional)Submit RequestSelect reason for cancellingDoctor did not join the consultBooked with wrong user detailsDoctor denied your prefarable mode of consultAudio Video IssuesOthers (Please specify)<br>html tag=BODY<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
micclass=WebElement<br>html tag=BODY<br>]]></Details>
<Time><![CDATA[09-04-2022 - 22:56:06]]></Time>
<TimeTick>1649525166</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="74" Source="Action1" SourceLine="220" >
<Disp><![CDATA["<iframe src='https://www.googl"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[<iframe src='https://www.googl.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[09-04-2022 - 22:56:06]]></Time>
<TimeTick>1649525166</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="75" Source="Action1" SourceLine="220" >
<Disp><![CDATA[<iframe src='https://www.googl.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Select reason for cancellingDo]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Select&nbsp;reason&nbsp;for&nbsp;cancellingDo"&nbsp;(of&nbsp;class&nbsp;WebList).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[09-04-2022 - 22:56:11]]></Time>
<TimeTick>1649525171</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Select reason for cancellingDo]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebList<br>Html Tag = UL<br>_xpath = //DIV[@id="menu-"]/DIV[3]/UL[@role="listbox"][1]<br>|Visible Items = 6<br>Visible = -1<br>Name = select<br>Items Count = 6<br>Html Id = <br>first item = Select reason for cancelling<br>default value = <br>DHTML Class = aph-438-MuiList-root aph-438-MuiMenu-list aph-438-MuiList-padding<br>acc_name = <br>]]></Details>
<Time><![CDATA[09-04-2022 - 22:56:11]]></Time>
<TimeTick>1649525171</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="90" status="Warning" nType="Description" Source="Action1" SourceLine="221" >
<Disp><![CDATA[Select reason for cancellingDo]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="89" status="Failed" nType="Run Error" Source="Action1" SourceLine="221" >
<Disp><![CDATA[Select reason for cancellingDo]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[09-04-2022 - 22:56:11]]></Time>
<TimeTick>1649525171</TimeTick>
<NodeArgs eType="General" icon="13" nRep="91" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="30" status="Failed" Source="Action1" SourceLine="218" >
<Disp><![CDATA[Apollo_4]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="25" status="Failed" Source="Action1" SourceLine="217" >
<Disp><![CDATA[Apollo]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="09-04-2022 - 22:55:37" eTime="09-04-2022 - 22:56:11" passed="1" failed="1" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="09-04-2022 - 22:55:37" eTime="09-04-2022 - 22:56:11" passed="1" failed="1" warnings="2" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test appnt Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>